[package]
name = "eternalcraft-launcher"
default-run = "eternalcraft-launcher"
version = "0.1.7"
description = "EternalCraft native game launcher"
authors = ["EternalCraft"]
edition = "2021"
rust-version = "1.90"

[lib]
name = "eternalcraft_launcher_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
atomic-write-file = "0.3"
base64 = "0.22"
mc-launcher-core = "=0.1.2"
minisign-verify = "0.2.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = "=0.39.6"
sha2 = "0.10"
reqwest = { version = "0.13.5", features = ["blocking", "json"] }
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
zip = "2.4.2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
toml = "1.1.7"
